//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""PreGame"",
            ""id"": ""5c865c2e-a060-4294-af60-681f73074a9f"",
            ""actions"": [
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""2a132572-66a2-42b1-a0c9-22a768feb62e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3efb9a03-59e6-40af-9bd0-29b79521275c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PreGame
        m_PreGame = asset.FindActionMap("PreGame", throwIfNotFound: true);
        m_PreGame_Start = m_PreGame.FindAction("Start", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PreGame
    private readonly InputActionMap m_PreGame;
    private List<IPreGameActions> m_PreGameActionsCallbackInterfaces = new List<IPreGameActions>();
    private readonly InputAction m_PreGame_Start;
    public struct PreGameActions
    {
        private @GameControls m_Wrapper;
        public PreGameActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Start => m_Wrapper.m_PreGame_Start;
        public InputActionMap Get() { return m_Wrapper.m_PreGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PreGameActions set) { return set.Get(); }
        public void AddCallbacks(IPreGameActions instance)
        {
            if (instance == null || m_Wrapper.m_PreGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PreGameActionsCallbackInterfaces.Add(instance);
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
        }

        private void UnregisterCallbacks(IPreGameActions instance)
        {
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
        }

        public void RemoveCallbacks(IPreGameActions instance)
        {
            if (m_Wrapper.m_PreGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPreGameActions instance)
        {
            foreach (var item in m_Wrapper.m_PreGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PreGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PreGameActions @PreGame => new PreGameActions(this);
    public interface IPreGameActions
    {
        void OnStart(InputAction.CallbackContext context);
    }
}
